// <auto-generated />
using System;
using LojaApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260108023542_UpdateMateriaPrimaEntity")]
    partial class UpdateMateriaPrimaEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LojaApp.Models.EntradaMateriais.EntradaMaterial", b =>
                {
                    b.Property<Guid>("IdEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataEntrada")
                        .HasColumnType("date");

                    b.Property<string>("IdMateriaPrima")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PesoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("TipoMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorUn")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdEntrada");

                    b.HasIndex("IdMateriaPrima");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("LojaApp.Models.Produtos.Categoria", b =>
                {
                    b.Property<string>("IdCategoria")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("LojaApp.Models.Produtos.Custos", b =>
                {
                    b.Property<string>("IdCusto")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DescricaoCusto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("IdProduto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("ValorCusto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdCusto");

                    b.HasIndex("IdProduto");

                    b.ToTable("Custos");
                });

            modelBuilder.Entity("LojaApp.Models.Produtos.Ingrediente", b =>
                {
                    b.Property<string>("IdIngrediente")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("IdProduto")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("IdMateriaPrima")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("QtdIngrediente")
                        .HasColumnType("int");

                    b.HasKey("IdIngrediente");

                    b.HasIndex("IdProduto");

                    b.HasIndex("IdMateriaPrima");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("LojaApp.Models.Produtos.Produto", b =>
                {
                    b.Property<string>("IdProduto")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("IdCategoria")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("MargemLucro")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PesoProduto")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UrlImg")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("medidaEnum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProduto");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("LojaApp.Models.Produtos.MateriaPrima", b =>
                {
                    b.Property<string>("IdMateriaPrima")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("QtdEstoque")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TpMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorTotalEstoque")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VlUn")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdMateriaPrima");

                    b.ToTable("MateriasPrimas");
                });

            modelBuilder.Entity("LojaApp.Models.EntradaMateriais.EntradaMaterial", b =>
                {
                    b.HasOne("LojaApp.Models.Produtos.MateriaPrima", "MateriaPrima")
                        .WithMany()
                        .HasForeignKey("IdMateriaPrima")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MateriaPrima");
                });

            modelBuilder.Entity("LojaApp.Models.Produtos.Custos", b =>
                {
                    b.HasOne("LojaApp.Models.Produtos.Produto", "Produto")
                        .WithMany("ListaCustos")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("LojaApp.Models.Produtos.Ingrediente", b =>
                {
                    b.HasOne("LojaApp.Models.Produtos.Produto", "Produto")
                        .WithMany("ListaIngredientes")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LojaApp.Models.Produtos.MateriaPrima", "MateriaPrima")
                        .WithMany()
                        .HasForeignKey("IdMateriaPrima")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Produto");

                    b.Navigation("MateriaPrima");
                });

            modelBuilder.Entity("LojaApp.Models.Produtos.Produto", b =>
                {
                    b.HasOne("LojaApp.Models.Produtos.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("LojaApp.Models.Produtos.Produto", b =>
                {
                    b.Navigation("ListaCustos");

                    b.Navigation("ListaIngredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
